
---
flags:
  SharedArrayBuffer: useSharedArrayBuffer
  Atomics: useSharedArrayBuffer
  Temporal: useTemporal
  ShadowRealm: useShadowRealm
  json-parse-with-source: useJSONSourceTextAccess
  iterator-sequencing: useIteratorSequencing
  explicit-resource-management: useExplicitResourceManagement
  import-defer: useImportDefer
  joint-iteration: useJointIteration
skip:
  features:
    - callable-boundary-realms
    - FinalizationRegistry.prototype.cleanupSome
    - decorators
    - source-phase-imports
    - await-dictionary
    - import-bytes
    - immutable-arraybuffer
    - error-stack-accessor
  paths:
    # Depends on the nonextensible-applies-to-private proposal which JSC has not implemented yet.
    - test/language/import/import-defer/evaluation-triggers/ignore-private-name-access.js
    # Incorrect tests, see https://github.com/tc39/test262/issues/4980
    - test/language/import/import-defer/evaluation-triggers/ignore-super-property-set-exported.js
    - test/language/import/import-defer/evaluation-triggers/ignore-super-property-set-not-exported.js
    - test/staging/Intl402
    - test/staging/JSON
  files:
    # https://github.com/claudepache/es-legacy-function-reflection
    - test/built-ins/ThrowTypeError/unique-per-realm-function-proto.js
    - test/built-ins/Function/prototype/restricted-property-arguments.js
    - test/built-ins/Function/prototype/restricted-property-caller.js

    # Skipping temporarily due to a bug with handling case-insensitive \p escapes
    - test/built-ins/RegExp/regexp-modifiers/add-ignoreCase-affects-slash-upper-p.js
    - test/built-ins/RegExp/regexp-modifiers/add-ignoreCase-affects-slash-lower-p.js
